#!/usr/bin/php -q
<?php
include(__DIR__."/lib/include.php");

try
{
  //parse params
  $args = parseParameters(array());
  if(isset($args[0]) && $args[0]==$_SERVER['PHP_SELF']) unset($args[0]);

  //test if file option is there
  if(!isset($args[1])) throw new Exception("missing configuration file path");
  $file = $args[1];

  //load buildkake config from default/custom
  $uConfig = new AppConfig(__DIR__.'/../config/buildkake.ini', null);
  $uConfig->init();

  //load builder configuration
  $bConfig = new BuildkakeConfig($file);
  $bConfig->init();

  //process configuration
  $bCore = new BuildkakeCore($bConfig->getProjectPath(), $bConfig->getDeps());
  $bCore->init();
  $bCore->process();
}
catch(Exception $e)
{
  errorMessage($e->getMessage());
}

var_dump($config);
//call the post build command
if(isset($config['build-command']) && $config['build-command']!="")
{
  $cmd = "cd $project_path; ";
  $cmd .= $config['build-command'];
  
  echo $cmd."\n";
  system($cmd);
}